$(function(){
const properties=[
{id:1,title:"Palm Grove Residency",type:"Apartment",city:"Nagpur",location:"Manish Nagar, Nagpur",price:18000,rating:4.8,badge:"Verified",image:"https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=82",lat:21.1075,lng:79.0892},
{id:2,title:"The Green Studio",type:"Studio",city:"Nagpur",location:"Dharampeth, Nagpur",price:12500,rating:4.7,badge:"Popular",image:"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=82",lat:21.1458,lng:79.0808},
{id:3,title:"Sapphire Heights",type:"Apartment",city:"Pune",location:"Viman Nagar, Pune",price:24500,rating:4.9,badge:"Top rated",image:"https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=82",lat:18.5679,lng:73.9143},
{id:4,title:"Lakeview Villa",type:"Villa",city:"Nagpur",location:"Hingna, Nagpur",price:32000,rating:4.6,badge:"New",image:"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=82",lat:21.0911,lng:78.9888},
{id:5,title:"Maple Corner Home",type:"Apartment",city:"Mumbai",location:"Powai, Mumbai",price:38000,rating:4.8,badge:"Verified",image:"https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=82",lat:19.1176,lng:72.9060},
{id:6,title:"Olive One-Bed",type:"Studio",city:"Nashik",location:"College Road, Nashik",price:14500,rating:4.7,badge:"Quiet pick",image:"https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=82",lat:20.0041,lng:73.7751}];
const currency=v=>new Intl.NumberFormat("en-IN").format(v);
function render(list){const g=$("#propertyGrid");g.empty();if(!list.length){$("#emptyState").removeClass("d-none");return}$("#emptyState").addClass("d-none");list.forEach(p=>{const s=localStorage.getItem("rentease-fav-"+p.id)==="1";g.append('<article class="property-card" data-property-id="'+p.id+'"><div class="property-image"><img src="'+p.image+'" alt="'+p.title+'" loading="lazy"><span class="property-badge">'+p.badge+'</span><button class="favorite-btn '+(s?"active":"")+'" type="button" aria-label="Save '+p.title+'"><i class="'+(s?"fa-solid":"fa-regular")+' fa-heart"></i></button></div><div class="property-body"><div class="property-meta"><span class="property-type">'+p.type+'</span><span class="property-rating"><i class="fa-solid fa-star"></i>'+p.rating+'</span></div><h3>'+p.title+'</h3><div class="property-location"><i class="fa-solid fa-location-dot"></i>'+p.location+'</div><div class="property-footer"><div class="property-price"><strong>₹'+currency(p.price)+'</strong><span> / month</span></div><a href="#contact" class="property-link" data-property="'+p.title+'">View details <i class="fa-solid fa-arrow-up-right-from-square"></i></a></div></div></article>')})}
function apply(){const l=$("#locationFilter").val().trim().toLowerCase(),t=$("#typeFilter").val(),b=$("#budgetFilter").val();const f=properties.filter(p=>(!l||[p.city,p.location,p.title].join(" ").toLowerCase().includes(l))&&(t==="all"||p.type===t)&&(b==="all"||p.price<=+b));render(f);$("#searchFeedback").text(f.length?f.length+" "+(f.length===1?"home":"homes")+" found — shortlist the ones that fit.":"No homes matched. Try broadening your search.")}
function reset(){$("#locationFilter").val("");$("#typeFilter").val("all");$("#budgetFilter").val("all");render(properties);$("#searchFeedback").text("Showing all featured homes.")}
function toast(msg){$("#toastMessage").text(msg);bootstrap.Toast.getOrCreateInstance(document.getElementById("appToast"),{delay:2600}).show()}
render(properties);$("#searchFeedback").text("Showing all featured homes.");$("#year").text(new Date().getFullYear());
$("#searchBtn").on("click",apply);$("#resetFilters,#emptyReset").on("click",e=>{e.preventDefault();reset()});$("#searchBox input").on("keydown",e=>{if(e.key==="Enter")apply()});
$("#propertyGrid").on("click",".favorite-btn",function(){const id=$(this).closest(".property-card").data("property-id"),p=properties.find(x=>x.id===id),a=$(this).toggleClass("active").hasClass("active");$(this).find("i").toggleClass("fa-solid",a).toggleClass("fa-regular",!a);localStorage.setItem("rentease-fav-"+id,a?"1":"0");toast(a?p.title+" added to favourites.":p.title+" removed from favourites.")});
$("#propertyGrid").on("click",".property-link",function(){toast("Property details for "+$(this).data("property")+" will be available in the next phase.")});
$(".auth-form").on("submit",function(e){e.preventDefault();if(!this.checkValidity()){$(this).addClass("was-validated");return}const login=this.id==="loginForm";bootstrap.Modal.getInstance(this.closest(".modal"))?.hide();toast(login?"Demo login submitted successfully.":"Account form submitted successfully.");this.reset();$(this).removeClass("was-validated")});
$(".nav-link").on("click",function(){$(".nav-link").removeClass("active");$(this).addClass("active");$(".navbar-collapse").removeClass("show")});
if(document.getElementById("map")){const map=L.map("map",{scrollWheelZoom:false}).setView([21.1458,79.0882],11);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenStreetMap contributors"}).addTo(map);properties.forEach(p=>L.marker([p.lat,p.lng]).addTo(map).bindPopup("<strong>"+p.title+"</strong><br>₹"+currency(p.price)+" / month"))}
const top=$("#scrollTop");$(window).on("scroll",function(){top.toggleClass("d-none",window.scrollY<500)});top.on("click",()=>window.scrollTo({top:0,behavior:"smooth"}));
});